Repository Aryan-Srivastava/College_Post, pull requests merged in 2023-02, with the labels that each got.

#12 Create CODE OF CONDUCT File
  CODE OF CONDUCT.md
  CONTRIBUTING.md
Labels: easy

#20 Fixes issue #5
  package.json
  src/App.js
  src/components/BlogCard.jsx
  src/components/CardBlocks.jsx
  src/components/SideBar.jsx
  src/components/SplitSection.jsx
  src/components/TopBar.jsx
  src/index.css
Labels: pwoc, Hard

#24 Made the About page responsive for mobile and tab devices
  src/components/CardBlocks.jsx
  src/components/SplitSection.jsx
  src/components/TopBar.jsx
  src/index.css
  src/pages/Home.jsx
Labels: pwoc, easy
